#!/usr/bin/env bash
# shellcheck disable=SC2034,SC1091

skills_title='🧩 Skills'
SKILLS_DIR="${HOME}/.agents/skills"

if [[ -n "${DOTFILES_PATH:-}" ]]; then
  SKILLS_DUMP_FILE_PATH="${SKILLS_DUMP_FILE_PATH:-${DOTFILES_PATH}/agents/skill-lock.yaml}"
else
  SKILLS_DUMP_FILE_PATH="${SKILLS_DUMP_FILE_PATH:-${HOME}/.agents/skill-lock.yaml}"
fi

. "${SLOTH_PATH:-}/scripts/package/src/lib/yaml.sh"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_json_read_value() {
  local file key value
  file="${1:-}"
  key="${2:-}"
  [[ -z "$file" || -z "$key" || ! -f "$file" ]] && return 1
  value="$(grep -o "\"${key}\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" "$file" | head -1 | sed 's/.*: *"//; s/"//')"
  printf '%s' "$value"
}

_json_read_array_flat() {
  local file key line
  file="${1:-}"
  key="${2:-}"
  [[ -z "$file" || -z "$key" || ! -f "$file" ]] && return 1

  line="$(tr '\n' ' ' < "$file" | grep -o "\"${key}\"[[:space:]]*:[[:space:]]*\[[^]]*\]" | head -1)"
  [[ -z "$line" ]] && return 1

  line="${line#*\[}"
  line="${line%\]}"
  echo "$line" | sed 's/[[:space:]]*"//g; s/"[[:space:]]*//g' | tr ',' '\n' | paste -sd ',' -
}

_dump_log() {
  local level msg
  level="${1:-info}"
  msg="${2:-}"
  printf '[skills::dump] [%s] %s\n' "$level" "$msg" >&2
}

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

skills::title() {
  echo -n "🧩 Skills"
}

skills::is_available() {
  return 0
}

skills::setup() {
  :
}

# ---------------------------------------------------------------------------
# P2: Discovery — primary (lockfile)
# ---------------------------------------------------------------------------

skills::_discover_skills_with_lockfiles() {
  local lock_file provider branch name cmd agents_csv

  [[ ! -d "$SKILLS_DIR" ]] && return 0

  while IFS= read -r -d '' skill_dir; do
    name="$(basename "$skill_dir")"
    lock_file="${skill_dir}/.skill-lock.json"

    [[ ! -f "$lock_file" ]] && continue

    provider="$(_json_read_value "$lock_file" "provider")"
    branch="$(_json_read_value "$lock_file" "branch")"
    cmd="$(_json_read_value "$lock_file" "command")"
    agents_csv="$(_json_read_array_flat "$lock_file" "agents")"

    if [[ -z "$provider" ]]; then
      _dump_log "warn" "Skipping '${name}': .skill-lock.json has no 'provider' field"
      continue
    fi

    [[ -z "$cmd" ]] && cmd="unknown"
    [[ -z "$branch" ]] && branch=""
    [[ -z "$agents_csv" ]] && agents_csv="unknown"

    printf '%s|%s|%s|%s|%s|lockfile\n' "$provider" "$branch" "$name" "$cmd" "$agents_csv"
  done < <(find "$SKILLS_DIR" -mindepth 1 -maxdepth 1 -type d -print0 2> /dev/null)
}

# ---------------------------------------------------------------------------
# P2: Discovery — fallback (package.json)
# ---------------------------------------------------------------------------

skills::_discover_skills_from_package_json() {
  local pkg_file name provider branch

  [[ ! -d "$SKILLS_DIR" ]] && return 0

  while IFS= read -r -d '' skill_dir; do
    name="$(basename "$skill_dir")"
    lock_file="${skill_dir}/.skill-lock.json"
    pkg_file="${skill_dir}/package.json"

    [[ -f "$lock_file" ]] && continue
    [[ ! -f "$pkg_file" ]] && continue

    provider="$(_json_read_value "$pkg_file" "name")"
    if [[ -z "$provider" ]]; then
      _dump_log "warn" "Skipping '${name}': package.json has no 'name' field"
      continue
    fi

    branch="$(git -C "$skill_dir" rev-parse --abbrev-ref HEAD 2> /dev/null || echo "master")"

    _dump_log "warn" "Skill '${name}' discovered via package.json fallback — not all install details may be accurate."
    printf '%s|%s|%s|%s|%s|package-json\n' "$provider" "$branch" "$name" "unknown" "unknown"
  done < <(find "$SKILLS_DIR" -mindepth 1 -maxdepth 1 -type d -print0 2> /dev/null)
}

# ---------------------------------------------------------------------------
# P2: Dump — orchestrate
# ---------------------------------------------------------------------------

skills::dump() {
  local dump_file="$SKILLS_DUMP_FILE_PATH"
  local input_file=""

  mkdir -p "$(dirname "$dump_file")"

  # Read from top-level .skill-lock.json (the source of truth)
  input_file="${HOME}/.agents/.skill-lock.json"
  [[ ! -f "$input_file" ]] && input_file="${DOTFILES_PATH}/.agents/.skill-lock.json"
  [[ ! -f "$input_file" ]] && input_file=""

  if [[ -z "$input_file" ]]; then
    _dump_log "info" "No .skill-lock.json found — writing empty lockfile."
    {
      yaml::write_value "format" "skill-lock-v1"
      echo "skills: []"
    } | yaml::write_document "$dump_file" "# Agent skills lockfile — generated by dot package dump"
    return 0
  fi

  # Parse .skill-lock.json with jq and produce YAML output
  local providers_yaml
  providers_yaml="$(jq -r '
    .skills // {} | to_entries | sort_by(.key) | .[] |
    "  - name: \(.key)\n    provider: \(.value.source // .value.provider // "unknown")\n    path: \(if .value.skillPath then .value.skillPath else "" end)"
  ' "$input_file" 2>/dev/null)" || {
    _dump_log "error" "Failed to parse .skill-lock.json — writing empty lockfile."
    {
      yaml::write_value "format" "skill-lock-v1"
      echo "skills: []"
    } | yaml::write_document "$dump_file" "# Agent skills lockfile — generated by dot package dump"
    return 0
  }

  (
    yaml::write_value "format" "skill-lock-v1"
    echo "skills:"
    echo "$providers_yaml"
  ) | yaml::write_document "$dump_file" "# Agent skills lockfile — generated by dot package dump"

  local provider_count
  provider_count="$(grep -c '^  - name:' "$dump_file" 2> /dev/null || echo 0)"
  _dump_log "info" "Dumped ${provider_count} providers from ${input_file}."
}

# ---------------------------------------------------------------------------
# P3: Import helpers
# ---------------------------------------------------------------------------

_import_log() {
  local level msg
  level="${1:-info}"
  msg="${2:-}"
  printf '[skills::import] [%s] %s\n' "$level" "$msg" >&2
}

# Emit a completed skill entry: provider|branch|skill_name|command|agents_csv
_emit_import_skill() {
  local p_name="$1" s_name="$2" s_cmd="$3" s_agents="$4"
  local skill_provider="$5" skill_path="$6"
  if [[ -n "$s_name" ]]; then
    local provider="${skill_provider:-${p_name%%#*}}"
    local path="${skill_path:-${s_cmd}}"
    printf '%s|%s|%s|%s\n' "$s_name" "$provider" "$path" "$s_agents"
  fi
}

# ---------------------------------------------------------------------------
# P3: YAML parsing — primary (yaml.sh-based)
# ---------------------------------------------------------------------------

# Emit a parse error with line number
_emit_parse_error() {
  local line_num="$1" msg="$2"
  _import_log "error" "Line ${line_num}: ${msg}"
}

skills::_parse_yaml_document() {
  local file="$1"
  [[ ! -f "$file" ]] && return 1

  local fmt
  fmt="$(yaml::read_value "$file" "format")" || {
    _import_log "error" "Failed to read 'format' from ${file}"
    return 1
  }

  local skill_name="" provider="" path="" agents=""
  local in_skills=false
  local line stripped indent leading
  local line_num=0

  while IFS= read -r line; do
    ((++line_num))
    [[ "$line" == \#* || -z "$line" ]] && continue

    leading="${line%%[![:space:]]*}"
    indent="${#leading}"
    stripped="${line:indent}"

    if [[ $indent -eq 0 ]]; then
      if [[ "$stripped" == "skills:"* ]]; then
        in_skills=true
      elif [[ "$stripped" == "format:"* || "$stripped" == "version:"* || "$stripped" == "description:"* ]]; then
        continue
      elif $in_skills; then
        _emit_import_skill "" "$skill_name" "" "" "$provider" "$path"
        break
      else
        _emit_parse_error "$line_num" "Unexpected top-level entry: '${stripped}'"
      fi
      continue
    fi

    $in_skills || continue

    if [[ $indent -eq 2 && "$stripped" == "- name:"* ]]; then
      _emit_import_skill "" "$skill_name" "" "" "$provider" "$path"
      skill_name=""
      provider=""
      path=""
      skill_name="${stripped#- name:}"
      skill_name="${skill_name## }"
      continue
    fi

    if [[ $indent -eq 4 ]]; then
      if [[ "$stripped" == "provider:"* ]]; then
        provider="${stripped#provider:}"
        provider="${provider## }"
      elif [[ "$stripped" == "path:"* ]]; then
        path="${stripped#path:}"
        path="${path## }"
      else
        _emit_parse_error "$line_num" "Expected 'provider:' or 'path:' at indent 4, got: '${stripped}'"
      fi
      continue
    fi
  done < "$file"

  _emit_import_skill "" "$skill_name" "" "" "$provider" "$path"
}

# ---------------------------------------------------------------------------
# P3: YAML parsing — fallback (raw line-by-line)
# ---------------------------------------------------------------------------

skills::_parse_yaml_raw() {
  local file="$1"
  [[ ! -f "$file" ]] && return 1

  local skill_name="" provider="" path=""
  local current_indent=0 prev_indent=0
  local line stripped indent leading

  while IFS= read -r line; do
    [[ "$line" == \#* || -z "$line" ]] && continue

    leading="${line%%[![:space:]]*}"
    indent="${#leading}"
    stripped="${line:indent}"

    # Track skill name (indent 2, "- name:")
    if [[ "$stripped" =~ ^-\ *name:\ *(.+)$ ]] && [[ $indent -eq 2 ]]; then
      _emit_import_skill "" "$skill_name" "" "" "$provider" "$path"
      skill_name="${BASH_REMATCH[1]}"
      provider=""
      path=""
      continue
    fi

    # Track provider (indent 4, "provider:")
    if [[ "$stripped" =~ ^provider:\ *(.+)$ ]] && [[ $indent -eq 4 ]]; then
      provider="${BASH_REMATCH[1]}"
      continue
    fi

    # Track path (indent 4, "path:")
    if [[ "$stripped" =~ ^path:\ *(.+)$ ]] && [[ $indent -eq 4 ]]; then
      path="${BASH_REMATCH[1]}"
      continue
    fi
  done < "$file"

  _emit_import_skill "" "$skill_name" "" "" "$provider" "$path"
}

# ---------------------------------------------------------------------------
# P3: Execute single install
# ---------------------------------------------------------------------------

skills::_execute_single_install() {
  local provider="$1"
  local path="$2"
  local agent="$3"
  local skill_name="${4:-}"

  if [[ -n "$skill_name" ]]; then
    local existing_lock="${SKILLS_DIR}/${skill_name}/.skill-lock.json"
    if [[ -f "$existing_lock" ]]; then
      _import_log "info" "Already installed: skill '${skill_name}'"
      return 0
    fi
  fi

  local cmd="npx"
  if command -v bunx &> /dev/null; then
    cmd="bunx"
  fi
  if [[ -n "$agent" ]]; then
    $cmd -y skills add "${provider}#${path}" --agent "$agent"
  else
    $cmd -y skills add "${provider}#${path}"
  fi
  return $?
}

# ---------------------------------------------------------------------------
# P3: Verify install
# ---------------------------------------------------------------------------

skills::_verify_install() {
  local skill_name="$1"
  local skill_dir="${SKILLS_DIR}/${skill_name}"

  [[ -d "$skill_dir" ]] || return 1
  [[ -f "${skill_dir}/.skill-lock.json" ]] || {
    _import_log "warn" "Skill '${skill_name}' installed but .skill-lock.json not found"
    return 0
  }
  return 0
}

# ---------------------------------------------------------------------------
# P3: Import — main
# ---------------------------------------------------------------------------

skills::import() {
  local import_file="$SKILLS_DUMP_FILE_PATH"
  local total=0 succeeded=0 failed=0

  if [[ ! -f "$import_file" ]]; then
    _import_log "error" "No skill-lock.yaml found at ${import_file}"
    return 1
  fi

  local fmt
  fmt="$(yaml::read_value "$import_file" "format" 2> /dev/null || echo "")"
  if [[ "$fmt" != "skill-lock-v1" ]]; then
    _import_log "error" "Invalid or missing format field in ${import_file} (expected 'skill-lock-v1')"
    return 1
  fi

  local parsed
  parsed="$(skills::_parse_yaml_document "$import_file")" || {
    _import_log "warn" "Primary parser failed — attempting fallback parser..."
    parsed="$(skills::_parse_yaml_raw "$import_file")" || {
      _import_log "error" "Failed to parse ${import_file} — both parsers failed"
      return 1
    }
  }

  [[ -z "$parsed" ]] && {
    _import_log "warn" "No entries found in ${import_file}"
    return 0
  }

  while IFS='|' read -r skill_name provider path agents_csv; do
    [[ -z "$skill_name" || -z "$provider" ]] && continue
    ((++total))

    if [[ -z "$path" ]]; then
      _import_log "warn" "Skipping entry: missing path (skill=${skill_name}, provider=${provider})"
      ((++failed))
      continue
    fi

    local entry_ok=true

    if [[ -n "$agents_csv" && "$agents_csv" != "unknown" ]]; then
      local saved_ifs="$IFS"
      local IFS=','
      for agent in $agents_csv; do
        IFS="$saved_ifs"
        agent="${agent#"${agent%%[![:space:]]*}"}"
        agent="${agent%"${agent##*[![:space:]]}"}"
        [[ -z "$agent" ]] && continue

        if skills::_execute_single_install "$provider" "$path" "$agent" "$skill_name"; then
          if skills::_verify_install "$skill_name"; then
            _import_log "info" "Installed '${skill_name}' for agent '${agent}'"
          else
            _import_log "warn" "'${skill_name}' installed for '${agent}' but verification incomplete"
          fi
        else
          _import_log "error" "Failed to install '${skill_name}' for agent '${agent}'"
          entry_ok=false
        fi
      done
      IFS="$saved_ifs"
    else
      if skills::_execute_single_install "$provider" "$path" "" "$skill_name"; then
        if skills::_verify_install "$skill_name"; then
          _import_log "info" "Installed '${skill_name}'"
        else
          _import_log "warn" "'${skill_name}' installed but verification incomplete"
        fi
      else
        _import_log "error" "Failed to install '${skill_name}'"
        entry_ok=false
      fi
    fi

    if $entry_ok; then
      ((++succeeded))
    else
      ((++failed))
    fi
  done <<< "$parsed"

  local msg
  msg="Import complete: ${total} total, ${succeeded} succeeded, ${failed} failed."
  _import_log "info" "$msg"
  printf '%s\n' "$msg"

  [[ $total -eq 0 ]] && return 1
  [[ $succeeded -gt 0 ]] && return 0
  return 1
}
