#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

dotfiles::apply_templating() {
  PRINT_PATH=$(dotfiles::separate_dotpath_if_defalut_path)
  if platform::is_macos; then
    sed -i '' -e "s|XXX_DOTFILES_PATH_XXX|$PRINT_PATH|g" "$DOTFILES_PATH/shell/zsh/.zshenv"
  else
    sed -i -e "s|XXX_DOTFILES_PATH_XXX|$PRINT_PATH|g" "$DOTFILES_PATH/shell/zsh/.zshenv"
  fi
}

dotfiles::separate_dotpath_if_defalut_path() {
  if grep -q "^$HOME*" <<< "$DOTFILES_PATH"; then
    ONLY_DOTPATH=$(echo $DOTFILES_PATH | awk -F"$HOME" '{ print $2 }')
    echo '$HOME'$ONLY_DOTPATH
  else
    echo '$DOTFILES_PATH'
  fi
}

##? Create the dotfiles structure
##?
##? Usage:
##?    create [dotfiles_path]
##?

# @todo Ensure it's not already created
cp -r "$DOTLY_PATH/dotfiles_template/"* "$DOTFILES_PATH/"

dotfiles::apply_templating

log::success "Done!"
