#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

dotfiles::apply_templating() {
  perl -i -pe"s|XXX_DOTFILES_PATH_XXX|$DOTFILES_PATH|g" "$DOTFILES_PATH/shell/zsh/.zshenv"
}

##? Create the dotfiles structure
##?
##? Usage:
##?    create [dotfiles_path]
##?

# @todo Ensure it's not already created
cp -r "$DOTLY_PATH/dotfiles_template/"* "$DOTFILES_PATH/"

dotfiles::apply_templating

log::success "Done!"
