#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Remove tracked files from control version (not the file) that are in the gitignore
##?
##? Usage:
##?   apply-gitignore
docs::parse "$@"

git ls-files --ignored --exclude-standard | xargs git rm --cached
