#!/usr/bin/env bash

set -euo pipefail

[[ -z "$SLOTH_PATH" ]] && exit 1

#shellcheck disable=SC1091
. "$SLOTH_PATH/scripts/core/_main.sh"
dot::load_library "init.sh"

##? Check iinit-script status
##?
##?
##? Usage:
##?   status [-h | --help]
##?   status [-v | --version]
##?   status [<script_name>]
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
docs::parse "$@"

SCRIPT_NAME="sloth init status"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

if [[ ${SLOTH_INIT_SCRIPTS:-true} != true ]]; then
  output::error "Init scripts are disabled"
  exit 1
fi

# Get the scripts
#shellcheck disable=SC2207
init_scripts=($(init::get_scripts))

# Check status, if user gives a script_name
if [ -n "${script_name:-}" ]; then

  if init::status "$script_name"; then
    output::solution "'$script_name' is enabled"
  else
    output::error "'$script_name' is disabled"
  fi

else

  # If there is no script_name, gives the status of all
  for item in "${init_scripts[@]}"; do
    {

      init::status "$item" &&
        output::solution "'$item'... Enabled."

    } || output::error "'$item'... Disabled."
  done

fi
