#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

symlinks::apply() {
  local -r CONFIG="$DOTFILES_PATH/symlinks/$1"
  shift

  echo
  "$DOTLY_PATH/modules/dotbot/bin/dotbot" -d "$DOTFILES_PATH" -c "$CONFIG" "$@"
  echo
}

##? Apply all symlinks
##?
##? Usage:
##?    apply
##?
docs::parse "$@"

output::write "This will replace your:"
output::write "    ~/.bashrc"
output::write "    ~/.bash_profile"
output::write "    ~/.zshrc"
output::write "    ~/.zshenv"
output::write "  Answer \"n\" if you prefer to do a backup first"
echo
output::question "Do you still want to continue? [Y/n]" "REPLY"
[[ "$REPLY" =~ ^[Nn] ]] && output::write "After you did the backup exec 'dot symlinks apply' and restart your terminal." && exit 1

symlinks::apply "conf.yaml"

if platform::is_macos; then
  if platform::is_macos_arm; then
    symlinks::apply "conf.macos.yaml"
  else
    symlinks::apply "conf.macos-intel.yaml"
  fi
else
  symlinks::apply "conf.linux.yaml"
fi

log::success "Done!"
