#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Show all changed files to <branch_name>
##?
##? Usage:
##?   changed-files
##?   changed-files <branch_name>
docs::parse "$@"

if [[ -z $branch_name ]]; then
  branch_name="main"
fi

git diff --name-only $branch_name
