#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Git log filtering
##?
##? Usage:
##?   pretty-log
docs::parse "$@"

commit=$(
  git log --graph \
    --color=always \
    --date=human \
    --format="%C(auto)%h%d %s %C(black)%C(bold)%ad by %an" |
    fzf --ansi --no-sort \
      --preview '
        __commit="$(echo {} | grep -o "[a-f0-9]\{7\}")";
          git diff-tree --no-commit-id --name-status -r ${__commit}
        ' \
      --preview-window right:35%
)

commit_hash=$(echo ${commit} | grep -o '[a-f0-9]\{7\}')

echo ${commit_hash} | tr -d '\n' | pbcopy
