#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Show a pretty git diff using fzf (and copy selected path to the clipboard)
##?
##? Usage:
##?   pretty-diff
docs::parse "$@"
script::depends_on git-delta

if (! git::is_in_repo); then
	echo "Not in a git repo!"
	exit 0
fi

file=$(git -c color.status=always status --short |
	fzf --height 100% --ansi \
		--preview '(git diff HEAD --color=always -- {-1} | sed 1,4d | delta --hunk-header-style=omit)' \
		--preview-window right:65% |
	cut -c4- |
	sed 's/.* -> //' |
	tr -d '\n')

vim "$file"
