#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
. "${SLOTH_PATH:-$DOTLY_PATH}/scripts/core/src/_main.sh"
dot::load_library "update.sh"
dot::load_library "autoupdate.sh"

##? Async autoupdate dotly to avoid load all core functions in default bash
##?
##? Usage:
##?    autoupdate
docs::parse "$@"

set +eu # Needed to use async
async autoupdate::sloth_updater autoupdate::sloth_success autoupdate::sloth_reject
