#!/usr/bin/env bash

set -euo pipefail

#shellcheck disable=SC1091
. "${SLOTH_PATH:-$DOTLY_PATH}/scripts/core/src/_main.sh"

##? Debug dotly
##?
##? Usage:
##?   debug
docs::parse "$@"
script::depends_on tail

file=${DOTLY_LOG_FILE:-$HOME/dotly.log}

tail -f "$file"
