#!/usr/bin/env zsh

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Short the current $PWD
##?
##? Usage:
##?    short_pwd

if [[ $(pwd) == "$HOME" ]]; then
  echo "~"
else
  echo ${${${:-/${(j:/:)${(M)${(s:/:)${(D)PWD:h}}#(|.)[^.]}}/${PWD:t}}//\/~/\~}/\/\//\/}
fi
