#!/usr/bin/env bash

set -euo pipefail

[[ -z "$SLOTH_PATH" ]] && exit 1

#shellcheck disable=SC1091
. "$SLOTH_PATH/scripts/core/_main.sh"
dot::load_library "update.sh"

##? Update dotly/sloth to the latest stable release
##?
##? Usage:
##?    update [--disable | --enable]
##?
##? Options:
##?    --disable  Deactivate the dotly update command
##?    --enable   Activate the dotly update command
##?
docs::parse "$@"

if ${disable:-enable}; then
  touch "$DOTFILES_PATH/.sloth_force_current_version"
  exit 0
elif ${enable:-false}; then
  rm -f "$DOTFILES_PATH/.sloth_force_current_version"
  exit 0
fi

update::update_local_sloth_module

if [[ -f "$DOTFILES_PATH/.sloth_updated" ]]; then
  output::answer '✅ dotly/sloth updated to the latest version'
else
  output::answer '👌 You already have latest dotly/sloth version'
fi
