#!/usr/bin/env bash

. "$DOTLY_PATH/scripts/core/_main.sh"
dot::load_library "package.sh"
# TODO If _registry is finally moved this should change
dot::load_library "_registry.sh" "$(dot::get_script_path)/recipes/"

##? Install a package
##?
##? Usage:
##?    add [-v | --version]
##?    add [-h | --help]
##?    add [--recipe-path <recipe_path>] <package_name> [--skip-recipe]
##?
##? Options:
##?    -h --help     Show script help
##?    -v --version  Show script version
##?
if ! ${DOTLY_INSTALLER:-false}; then
  docs::parse "$@"
else
  package_name=""
  skip_recipe=false
  recipe_path="$(dot::get_script_path)/recipes/"
  while $# -gt 0; do
    case "$1" in
      --recipe-path)
        if [[ "$2" != "_registry" ]]; then
          recipe_path="$2"
        fi
        shift 2
        ;;
      --skip-recipe)
        skip_recipe=true; shift
        ;;
      --version|-v)
        version=true; shift
        ;;
      --help|-h)
        help=true; shift
        ;;
      *)
        package_name="$1"; shift
        ;;
    esac
  done
fi

if [[ $# -lt 1 ]]; then
  exit 1
fi

export PATH="$HOME/.cargo/bin:$PATH"

SCRIPT_NAME="lazy package add"
SCRIPT_VERSION="3.0.0"

if ${version:-}; then
  output::write "${SCRIPT_NAME} v${SCRIPT_VERSION}"
  exit 0
elif ${help:-}; then
  grep '^##?' "$0" | tr '##?' ' '
  exit 0
fi

# No package
[[ -z "${package_name:-}" ]] && exit 1

export PATH="$HOME/.cargo/bin:$PATH"

package::is_installed "$package_name" && log::success "$package_name already installed" && exit 0

if [[ -z "$skip_recipe" ]] &&\
   [[ -n "$(registry::recipe_exists "$package_name" "${recipe_path:-}")" ]] &&\
   registry::install "$package_name" "${recipe_path:-}" &&\
   registry::is_installed "$package_name" "${recipe_path:-}"
then
  output::write "✅ \`$package_name\` installed"

  exit 0
else
  package::command install "$package_name" 2>&1 | log::file "Trying to install $package_name using $package_manager" || true

  if package::is_installed "$package_name"; then
    output::write "✅ \`$package_name\` installed"

    exit 0
  fi
fi

if ! platform::command_exists "$package_name" && ! registry::is_installed "$package_name"; then
  output::write "❌ \`$package_name\` could not be installed"

  exit 1
fi
