#!/usr/bin/env bash

. "$DOTLY_PATH/scripts/core/_main.sh"

##? Some brew utils.
##?   - If cleanup does not receive any param will take your
##?     dumped Brewfile from dotly if exist. If does not exists
##?     and you don't provide a Brewfile will do nothing.
##?
##? Usage:
##?   brew list_installed
##?   brew cleanup [<optional_path_brewfile>]
docs::parse "$@"

case $1 in
"list_installed")
  brew leaves
  ;;
"cleanup")
  HOMEBREW_DUMP_FILE_PATH=${optional_path_brewfile:-"$DOTFILES_PATH/os/mac/brew/Brewfile"}
  cleanup_cmd="$(which brew) bundle --file=\"${HOMEBREW_DUMP_FILE_PATH}\" --force cleanup"
  output::write "This will execute the command... "
  output::write "    $cleanup_cmd"
  if [[ -f $HOMEBREW_DUMP_FILE_PATH ]]; then
    output::yesno "Still want to perform the action" &&\
      $(which brew) bundle --file="${HOMEBREW_DUMP_FILE_PATH}" --force cleanup
    output::yesno "Do you want to execute additional 'brew cleanup'" &&\
      $(which brew) cleanup
  else
    output::error "No Brewfile found"
  fi
  ;;
*)
  exit 1
  ;;
esac
