#!/usr/bin/env bash

set -euo pipefail

[[ -z "${DOTLY_PATH:-$SLOTH_PATH}" ]] && exit 1

#shellcheck disable=SC1091
. "${DOTLY_PATH:-$SLOTH_PATH}/scripts/core/_main.sh"
dot::load_library "package.sh"
dot::load_library "_registry.sh" "$(dot::get_script_path)/recipes/"

##? Install a package
##?
##? Usage:
##?    check [-v | --version]
##?    check [-h | --help]
##?    check [--recipe-path <recipe_path>] <package_name> [--skip-recipe]
##?
##? Options:
##?    -h --help     Show script help
##?    -v --version  Show script version
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
if ! ${DOTLY_INSTALLER:-false} && package::is_installed "docpars"; then
  docs::parse "$@"
else
  package_name=""
  version=false
  help=false
  recipe_path="$(dot::get_script_path)/recipes/"
  while [[ $# -gt 0 ]]; do
    case "$1" in
    --recipe-path)
      if [[ "$2" != "_registry" ]]; then
        recipe_path="$2"
      fi
      shift 2
      ;;
    --version | -v)
      version=true
      shift
      ;;
    --help | -h)
      help=true
      shift
      ;;
    *)
      package_name="$1"
      shift
      ;;
    esac
  done
fi

SCRIPT_NAME="lazy package check"
SCRIPT_VERSION="1.0.0"
package_name="$(str::to_lower "$package_name")"

if ${version:-}; then
  output::write "${SCRIPT_NAME} v${SCRIPT_VERSION}"
  exit 0
elif ${help:-}; then
  grep '^##?' "$0" | tr '##? ' ' '
  exit 0
elif [[ -z "${package_name:-}" ]]; then
  output::error "No package name provided"
  exit 1
fi

if [[ "$package_name" != "docpars" ]]; then
  script::depends_on docpars
fi

if { [[ "$package_name" == "docpars" ]] && registry::is_installed docpars "$recipe_path"; } ||
  { [[ "$package_name" != "docpars" ]] && package::is_installed "$package_name"; }; then
  log::success "$package_name already installed" && exit 0
fi

log::error "$package_name is not installed" && exit 1
