#!/usr/bin/env bash

. "$DOTLY_PATH/scripts/core/_main.sh"
. "$DOTLY_PATH/scripts/package/src/dump.sh"

##? Dump all installed packages from:
##?  * Brew
##?  * Apt
##?  * Snap
##?  * Python
##?  * Volta.sh or NPM
##?
##? Usage:
##?   dump
docs::parse "$@"

platform::command_exists brew && package::brew_dump && output::answer "Brew apps dumped on $HOMEBREW_DUMP_FILE_PATH"

platform::command_exists apt-mark && package::apt_dump && output::answer "Apt apps dumped on $APT_DUMP_FILE_PATH"

platform::command_exists snap && package::snap_dump && output::answer "Snap apps dumped on $SNAP_DUMP_FILE_PATH"

platform::command_exists pip3 && package::python_dump && output::answer "Python apps dumped on $PYTHON_DUMP_FILE_PATH"

if platform::command_exists volta; then
  package::volta_dump && output::answer "Volta apps dumped on $VOLTA_DUMP_FILE_PATH"
elif platform::command_exists npm; then
  package::npm_dump && output::answer "NPM apps dumped on $NPM_DUMP_FILE_PATH"
fi

output::solution 'All packages dumped'
