#!/usr/bin/env bash

source "$DOTLY_PATH/scripts/core/_main.sh"
source "$DOTLY_PATH/scripts/package/src/dump.sh"

##? Dump all installed packages from:
##?  * Brew
##?  * Apt
##?  * Snap
##?  * Python
##?  * Volta.sh or NPM
##?  * Winget
##?
##? Usage:
##?   dump
docs::parse "$@"

platform::command_exists brew && package::brew_dump && output::answer "Brew apps dumped on $HOMEBREW_DUMP_FILE_PATH"

platform::command_exists apt-mark && package::apt_dump && output::answer "Apt apps dumped on $APT_DUMP_FILE_PATH"

platform::command_exists snap && package::snap_dump && output::answer "Snap apps dumped on $SNAP_DUMP_FILE_PATH"

platform::command_exists pip3 && package::python_dump && output::answer "Python apps dumped on $PYTHON_DUMP_FILE_PATH"

if platform::command_exists volta; then
	package::volta_dump && output::answer "Volta apps dumped on $VOLTA_DUMP_FILE_PATH"
elif platform::command_exists npm; then
	package::npm_dump && output::answer "NPM apps dumped on $NPM_DUMP_FILE_PATH"
fi
platform::command_exists pacman && package::pacman_dump && output::answer "Pacman apps dumped on $PACMAN_DUMP_FILE_PATH"
platform::command_exists winget.exe && package::winget_dump && output::answer "Windows apps dumped on $WINGET_DUMP_FILE_PATH"

output::write 'All packages dumped'
