#!/usr/bin/env bash

source "$DOTLY_PATH/scripts/core/_main.sh"
source "$DOTLY_PATH/scripts/package/utils/dump.sh"

##? Dump all installed packages from:
##?  * Brew
##?  * Python
##?  * NPM
##?
##? Usage:
##?   dump
docs::parse "$@"

platform::is_macos && package::brew_dump && output::answer "Brew apps dumped on $HOMEBREW_DUMP_FILE_PATH"

platform::command_exists pip3 && package::python_dump && output::answer "Python apps dumped on $PYTHON_DUMP_FILE_PATH"
platform::command_exists npm && package::npm_dump && output::answer "NPM apps dumped on $NPM_DUMP_FILE_PATH"

output::solution 'All packages dumped'
