#!/usr/bin/env bash

source "$DOTLY_PATH/scripts/core/_main.sh"
source "$DOTLY_PATH/scripts/package/src/dump.sh"

##? Import previously dumped packages from:
##?  * Brew
##?  * Python
##?  * Volta or NPM
##?
##? Usage:
##?   import
docs::parse "$@"

output::write "🎩 Let's import your packages (this could take a while)"

platform::command_exists brew && output::header "Importing Brew apps from $HOMEBREW_DUMP_FILE_PATH" && package::brew_import

platform::command_exists apt-mark && output::header "Importing Apt apps from $APT_DUMP_FILE_PATH" && package::apt_import

platform::command_exists snap && output::header "Importing Snap apps from $SNAP_DUMP_FILE_PATH" && package::snap_import

platform::command_exists pip3 && output::header "Importing Python apps from $PYTHON_DUMP_FILE_PATH" && package::python_import

if platform::command_exists volta; then
    output::header "Importing Volta apps from $VOLTA_DUMP_FILE_PATH" && package::volta_import
elif platform::command_exists npm; then
    output::header "Importing NPM apps from $NPM_DUMP_FILE_PATH" && package::npm_import
fi

output::solution 'All packages imported'
