#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Install a package
##?
##? Usage:
##?    add [package_name]
##?

package_name="$1"

platform::command_exists "$package_name" && log::success "$package_name is already installed" && exit 0

_installing
for pkg_mgr in apt pkg yum dnf port emerge pacman brew npm; do
  dot pkg proxy $pkg_mgr add "$package" && exit 0 || true
done
exit 234
