#!/usr/bin/env bash

set -uo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"
source "$DOTLY_PATH/scripts/package/src/package_managers/brew.sh"
source "$DOTLY_PATH/scripts/package/src/package_managers/cargo.sh"
source "$DOTLY_PATH/scripts/package/src/package_managers/composer.sh"
source "$DOTLY_PATH/scripts/package/src/package_managers/gem.sh"
source "$DOTLY_PATH/scripts/package/src/package_managers/mas.sh"
source "$DOTLY_PATH/scripts/package/src/package_managers/npm.sh"
source "$DOTLY_PATH/scripts/package/src/package_managers/pip.sh"

##? Update all packages
##?
##? Usage:
##?   update_all
docs::parse "$@"

output::h1_without_margin "♻️  Updating all the apps on your system"
output::write "If you want to debug what's happening behind the scenes, you can execute \`dot self debug\` in parallel."

platform::command_exists mas && output::h2 '🍎 App Store' && mas::update_all
platform::command_exists brew && output::h2 '🍺 Brew' && brew::update_all
platform::command_exists pip3 && output::h2 '🐍 pip' && pip::update_all
platform::command_exists composer && output::h2 '🐘 Composer' && composer::update_all
platform::command_exists gem && output::h2 '♦️  gem' && gem::update_all
platform::command_exists npm && output::h2 '🌈 npm' && npm::update_all
platform::command_exists cargo && output::h2 '📦 cargo' && cargo::update_all

platform::command_exists tldr && output::h2 '📜 tldr database' && tldr --update >/dev/null 2>&1 && output::answer "Database updated"

output::h2 "👽 Zim Framework" && zsh "$ZIM_HOME/zimfw.zsh" upgrade 2>&1 | log::file "Upgrading Zim" && zsh "$ZIM_HOME/zimfw.zsh" update 2>&1 | log::file "Updating Zim" && output::answer "Done"

output::h2 "🌚 dotly completions" && dot shell zsh reload_completions >/dev/null 2>&1 && output::answer "Done"

output::empty_line
output::write '👌 All your packages have been successfully updated'
