#!/usr/bin/env bash

[[ -z "$DOTLY_PATH" ]] && exit 1

. "$DOTLY_PATH/scripts/core/_main.sh"
. "$DOTLY_PATH/scripts/dotly/lib/marketplace.sh"

##? Get or delete the cache for searching and installing scripts from dotly
##? marketplace.
##? 
##?
##? Usage:
##?   cache [-h | --help]
##?   cache [-v | --version]
##?   cache [--async] [--force]
##?   cache [--delete]
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?   --async       Download the cache in async mode. Async makes this script
##?                 run silently.
##?   --force       Delete the current cache and recreate it. This can be used
##?                 with --async option.
##?   --delete      Delete the current cache. Just perform a deletion.
##?
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
docs::parse "$@"

SCRIPT_NAME="dot dotly cache"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

create_asycn_cache() {
  marketplace::create_cache_tree >/dev/null 2>&1
}

success() {
  return # Not message when all work
}

reject () {
  output::error "Cache could not be created"
}

! ${async:-} && output::header "Marketplace cache"

if ${delete:-}; then
  output::answer "Cleaning marketplace cache"
  marketplace::clean_cache
  output::answer "Marketplace cache cleaned"
else
  if ${force_cache:-}; then
    ! ${async:-} && output::answer "Cleaning marketplace cache"
    marketplace::clean_cache
    ! ${async:-} && output::answer "Marketplace cache cleaned"
  fi

  if ${async:-}; then
    marketplace::check_cache_folder_should_be_created && async create_asycn_cache success reject
  else
    output::answer "Creating the cache if necessary"
    { marketplace::check_cache_folder_should_be_created && marketplace::create_cache_tree; } || output::error "Any error happened during the cache creation"
    output::header "End of Marketplace cache"
  fi
fi