#!/usr/bin/env bash

[[ -z "$DOTLY_PATH" ]] && exit 1

. "$DOTLY_PATH/scripts/core/_main.sh"

##? Install script from dotly marketplace
##? 
##?
##? Usage:
##?   install [-h | --help]
##?   install [-v | --version]
##?   install [-y | --yes] <context> <script>
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?   -y --yes      No prompt when installing a script, it will be overwrite
##?                 if exists.
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
docs::parse "$@"

SCRIPT_NAME="dot dotly install"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

# Here begin your script

case $1 in
# Any subcommand should be here
*)
  exit 1
  ;;
esac