#!/usr/bin/env bash

set -euo pipefail

. "$DOTLY_PATH/scripts/core/_main.sh"
dot::load_library "dotly_autoupdate.sh"

##? Async autoupdate dotly to avoid load all core functions in default bash
##?
##? Usage:
##?    autoupdate
docs::parse "$@"

set +eu # Needed to use async
async autoupdate::dotly_updater autoupdate::dotly_success autoupdate::dotly_reject