#!/usr/bin/env bash

set -euo pipefail

. "$DOTLY_PATH/scripts/core/_main.sh"
. "$DOTLY_PATH/scripts/self/src/autoupdate.sh"

##? Async autoupdate dotly to avoid load all core functions in default bash
##?
##? Usage:
##?    autoupdate
docs::parse "$@"

set +eu # Needed to use async
async autoupdate::updater autoupdate::success autoupdate::reject