#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"
source "$DOTLY_PATH/scripts/self/utils/autoupdate.sh"

##? Async autoupdate dotly to avoid load all core functions in default bash
##?
##? Usage:
##?    autoupdate
docs::parse "$@"

set +eu # Needed to use async
async "autoupdate::updater /Users/gtrabanco/MyCodes/dotly2" autoupdate::success autoupdate::reject