#!/usr/bin/env bash

set -euo pipefail

. "$DOTLY_PATH/scripts/core/_main.sh"

##? Debug dotly
##?
##? Usage:
##?   debug
docs::parse "$@"
script::depends_on tail

file=${DOTLY_LOG_FILE:-$HOME/dotly.log}

tail -f "$file"
