#!/usr/bin/env bash

source "$DOTLY_PATH/scripts/core/_main.sh"
source "$DOTLY_PATH/scripts/self/utils/install.sh"

export ZIM_HOME="$DOTFILES_PATH/.zim"
export PATH="$HOME/.cargo/bin:$PATH"

if platform::is_macos; then
  output::answer "🍎 Setting up macOS platform"
  install_macos_custom
fi

script::depends_on docpars fzf zsh python

##? Install dotly and setup dotfiles
##?
##? Usage:
##?    install
docs::parse "$@"

output::answer "Creating dotfiles structure"
"$DOTLY_PATH/bin/dot" dotfiles create | log::file "Creating dotfiles structure" || exit 1

# @todo Backup if exists before
output::answer "Setting up symlinks"
"$DOTLY_PATH/bin/dot" symlinks apply | log::file "Applying symlinks" || true
touch "$HOME/.z"

if ! str::contains zsh "$SHELL"; then
  output::answer "Setting zsh as the default shell"
  sudo chsh -s "$(command -v zsh)" | log::file "Setting zsh as default shell"
fi

output::answer "Installing Zim"
curl -fsSL --create-dirs -o "$ZIM_HOME/zimfw.zsh" https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh 2>&1 | log::file "Downloading zimfw.zsh" && zsh "$ZIM_HOME/zimfw.zsh" install 2>&1 | log::file "Installing Zim"

output::answer "Installing completions"
"$DOTLY_PATH/bin/dot" shell zsh reload_completions

output::answer "Executing custom restoration scripts"
install_scripts_path="$DOTFILES_PATH/restoration_scripts"
if [ -d "$install_scripts_path" ]; then
  find "$install_scripts_path" -mindepth 1 -maxdepth 1 -type l,f -name '*.sh' |
    sort |
    while read -r install_script; do
      { [[ -x "$install_script" ]] && . "$install_script" | log::file "Executing afterinstall: $(basename "$install_script")"; } || {
        output::error "Install script error in $(basename "$install_script")"
      }
    done
fi
