#!/usr/bin/env bash

source "$DOTLY_PATH/scripts/core/_main.sh"

##? List all dotly related bash files
##?
##? Usage:
##?    list_bash_files
if [ "$1" == "-h" ] || [ "$1" = "--help" ]; then
  docs::parse "$@"
fi

grep "#!/usr/bin/env bash" "$DOTLY_PATH"/{bin,dotfiles_template,scripts,shell,installer,restore} -R | awk -F':' '{print $1}'
find "$DOTLY_PATH"/{bin,dotfiles_template,scripts,shell} -type f -name "*.sh"
