#!/usr/bin/env bash

set -uo pipefail
#set +e # Avoid crash if any function return false

[[ -z "$DOTLY_PATH" ]] && exit 1

. "$DOTLY_PATH/scripts/core/_main.sh"
. "$DOTLY_PATH/scripts/core/templating.sh"

##?  Executes migration scripts for dotfiles. If your dotly is updated and no
##? script version is provided then try to guess the latest necessary migration
##? script.
##?
##? Usage:
##?   migration [-h | --help]
##?   migration [-v | --version]
##?   migration [<to_version>]
##?
##? Options:
##?   -h --help         Show this help
##?   -v --version      Show the program version
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
docs::parse "$@"

SCRIPT_NAME="dot self version"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

output::header "DOTLY migration wizard"

[[ -f "$DOTFILES_PATH/.dotly_updated" ]] && [[ -z "$to_version" ]] && to_version="$(uptate::migration_script_exits)"

if ! ${to_version:-false} || [[ ! -x "$DOTLY_PATH/migration/$to_version" ]]; then
  to_version="$(find "$DOTLY_PATH/migration/" -name "*" -type f,l -executable -print0 -exec echo {} \; | xargs -I _ basename _ | sort --reverse | fzf --header "Select migration script version")"
fi

if [[ -n "$to_version" ]]; then
  output::answer "You will execute migration script for '$to_version' this could"
  output::write "result in a damage of your current dotfiles if they are not"
  output::write "organized as expected."
  output::empty_line
  
  ! output::yesno "Sure you want to continue" && exit 1
  output::empty_line

  . "$DOTLY_PATH/migration/$to_version"
fi

if [[ -n "$to_version" ]] && { [[ -f "$DOTLY_PATH/symlinks/$to_version.yaml" ]] || [[ -f "$DOTLY_PATH/symlinks/$to_version.yml" ]]; }; then
  "$DOTLY_PATH/bin/dot" symlinks update "$to_version"
fi
