#!/usr/bin/env bash

set -euo pipefail

. "$DOTLY_PATH/scripts/core/_main.sh"
. "$DOTLY_PATH/scripts/self/src/update.sh"

##? Update dotly to the latest stable release
##?
##? Usage:
##?    update [--disable | --enable]
##?
##? Options:
##?    --disable  Deactivate the dotly update command
##?    --enable   Activate the dotly update command
##?
docs::parse "$@"

if ${disable:-enable}; then
  touch "$DOTFILES_PATH/.dotly_force_current_version"
  exit 0
elif ${enable:-false}; then
  rm -f "$DOTFILES_PATH/.dotly_force_current_version"
  exit 0
fi

update::update_local_dotly_module

output::answer '✅ dotly updated to the latest version'
