#!/usr/bin/env bash

set -euo pipefail

#shellcheck source=/dev/null
. "$DOTLY_PATH/scripts/core/_main.sh"
dot::get_script_src_path "update.sh"

##? Update dotly to the latest stable release
##?
##? Usage:
##?    update [--disable | --enable]
##?
##? Options:
##?    --disable  Deactivate the dotly update command
##?    --enable   Activate the dotly update command
##?
docs::parse "$@"

if ${disable:-enable}; then
  touch "$DOTFILES_PATH/.dotly_force_current_version"
  exit 0
elif ${enable:-false}; then
  rm -f "$DOTFILES_PATH/.dotly_force_current_version"
  exit 0
fi

update::update_local_dotly_module

if [[ -f "$DOTFILES_PATH/.dotly_updated" ]]; then
  output::answer '✅ dotly updated to the latest version'
else
  output::answer '👌 You already have latest dotly version'
fi
