#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Update dotly to the latest stable release
##?
##? Usage:
##?    update
docs::parse "$@"

cd "$DOTLY_PATH"
git pull >/dev/null 2>&1
git submodule update --init --recursive >/dev/null 2>&1

dot shell zsh reload_completions

output::answer '✅ dotly updated to the latest version'
