#!/usr/bin/env bash

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Apply opinionated mac defaults
##?
##? Usage:
##?   apply_defaults
docs::parse "$@"

sh "$DOTLY_PATH/scripts/mac/utils/defaults.sh"
