#!/usr/bin/env bash

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Some brew utils
##?
##? Usage:
##?   brew list_installed
docs::parse "$@"

case $1 in
"list_installed")
  brew leaves
  ;;
*)
  exit 1
  ;;
esac
