#!/usr/bin/env bash

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Some defaults utils
##?
##? Usage:
##?   defaults view_changed
docs::parse "$@"

case $1 in
"view_changed")
  current_defaults_path=$(mktemp)
  defaults read >"$current_defaults_path"

  git diff -w --no-index "$DOTLY_PATH/scripts/mac/utils/macos-11.0-defaults" "$current_defaults_path" | delta --side-by-side
  ;;
*)
  exit 1
  ;;
esac
