#!/usr/bin/env bash

echo "This is a script ran by the restoration process. You can add yours inside '$DOTFILES_PATH/restore_scripts'"
echo
echo "Self install scripts must have chmod u+x to run"
echo
