#!/usr/bin/env bash

. "$DOTLY_PATH/scripts/core/_main.sh"

##? View all or selected ssh configurations
##? 
##?
##? Usage:
##?   view [-h | --help]
##?   view [-v | --version]
##?   view [<ssh_alias_or_file>]
##?
##? Options:
##?   -h --help                                    Show this help
##?   -v --version                                 Show the program version
##?   view                                         View all configuration files
##?   view [<ssh_alias_or_file>]                   View configuration file or alias
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.co>

# Options part its important because assign short and long version of the params
docs::parse "$@"

SCRIPT_NAME="dot ssh view"
SCRIPT_VERSION="1.0.0"

# Print name and version
if $version; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

"$DOTLY_PATH/bin/dot" ssh edit --view "${ssh_alias_or_file:-}"