#!/usr/bin/env bash

[[ -z "$DOTLY_PATH" ]] && exit 1

. "$DOTLY_PATH/scripts/core/_main.sh"
. "$DOTLY_PATH/scripts/secrets/lib/secrets.sh"

##? Apply stored secrets aliases
##? 
##?
##? Usage:
##?   apply [-h | --help]
##?   apply [-v | --version]
##?   apply revert
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?   revert        Unapply all aliases of stored files. Useful when
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
docs::parse "$@"

SCRIPT_NAME="dot secrets load"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

case "$1" in
"revert")
  output::header "Reverting secrets"
  if secrets::revert; then
    output::empty_line
    output::solution "Reverted"
  else
    output::error "Could not be reverted"
  fi
  ;;
*)
  output::header "Applying secrets"
  secrets::apply
  ;;
esac
