#!/usr/bin/env bash

[[ -z "$DOTLY_PATH" ]] && exit 1

. "$DOTLY_PATH/scripts/core/_main.sh"
. "$DOTLY_PATH/scripts/secrets/lib/secrets_files_helpers.sh"

##? Handle stored secrets
##? 
##?
##? Usage:
##?   file [-h | --help]
##?   file [-v | --version]
##?   file [-p | --prompt] [-y | --yes] <item_path> [<secrets_subfolder>]
##?   file edit [-n | --no-sync] [-y | --yes] [<item_path> [<new_symlink_path>]] 
##?   file delete [-n | --no-sync] [-y | --yes] [<secret_path>]
##?   file view_aliases
##?   file view_stored_files
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?   -p --prompt   Ask subfolder path to store the file
##?   -n --no-sync  Do not sync changes. This option ignore --yes because
##?                 sync command won't be executed.
##?   -y --yes      No prompt about if you are sure you want to sync your
##?                 secrets repository.
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
docs::parse "$@"

SCRIPT_NAME="dot secrets file"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

case $1 in
"view_aliases")
  secrets::get_all_aliases | secrets::fzf "View secret aliases"
  ;;
"view_files")
  secrets::find --exclude files | secrets::fzf "View secet stored files"
  ;;
"delete")
  # Provided file
  if [[ -n "${2:-}" ]]; then
    file_secret_path="$(secrets::check_exists "files/$2")"
    if [[ -z $file_secret_path ]]; then
      output::error "🗃 Eror 404: File not found"
      exit 1
    fi

    secrets::remove_symlink_by_stored_file "$2"
    exit 0
  fi

  # Not provided file
  deleted_items=($(secrets::find --exclude files | secrets::fzf "Select file(s) to be deleted"))
  for item in "${deleted_items[@]}"; do
    secrets::remove_symlink_by_stored_file "$item"
  done
  ;;
"edit")
  echo "Not implemented"
  # TODO Edit current symlink to another one for secret file
  ;;
"restore")
  ;;
*)
  if $prompt && [[ -z "${secrets_subfolder:-}" ]]; then
    output::question "Relative path inside secrets files subfolder" "secrets_subfolder"
  fi
  
  secrets::store_file "$item_path" "${secrets_subfolder:-}"
  ;;
esac

# TODO enable sync
# if ! $no_sync; then
#   if $yes; then
#     "$DOTLY_PATH/bin/dot" secrets sync --yes
#   else
#     "$DOTLY_PATH/bin/dot" secrets sync
#   fi
# fi
