#!/usr/bin/env bash

[[ -z "$DOTLY_PATH" ]] && exit 1

. "$DOTLY_PATH/scripts/core/_main.sh"
. "$DOTLY_PATH/scripts/secrets/lib/secrets.sh"

##? Hide secrets values replacing values with 1pass Application Support Applications ApuntesLogicaCompletos-norm.pdf Cisco Packet Tracer 8.0.0 Creative Cloud Files Desktop Documents Downloads Library Movies Music MyCodes MyTools Pictures Public bin curl.sh dotly.log go-pear.phar mycroft.sh package.json password-prepared.csv pear publickey screenkey.sh torquemada
##? 
##?
##? Usage:
##?   hide [-h | --help]
##?   hide [-v | --version]
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
docs::parse "$@"

SCRIPT_NAME="dot secrets hide"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

secrets::hide_vars