#!/usr/bin/env bash

[[ -z "$DOTLY_PATH" ]] && exit 1

. "$DOTLY_PATH/scripts/core/_main.sh"
. "$DOTLY_PATH/scripts/secrets/lib/install_needed_soft_and_vars.sh"

secrets::check_remote_repository_exists() {
  git ls-remote "$1" >/dev/null 2>&1
}

##? Initialize a secrets repository. Private repository to store your secrets.
##?  - Without the url it will start the repository locally with 'secrets' as
##?    name if not exists.
##?  - With url that not yet exists it will initialize a new secrets repository
##?    and add that url to remote origin.
##?  The repository is initilized as git submodule in $DOTLY_SECRETS_MODULES_PATH.
##?
##?         ⚠️ IT IS RECOMMENDED TO USE SSH GIT URLS ⚠️
##?
##? Usage:
##?   init [-h | --help]
##?   init [-v | --version]
##?   init [-r | --recreate] <git_repository_ssh_url> [<branch>]
##?   
##?
##? Options:
##?   -h --help      Show this help
##?   -v --version   Show the program version
##?   -r --recreate  Delete your current secrets repository and create a new one
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
docs::parse "$@"

SCRIPT_NAME="dot secrets init"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

if ! secrets::check_remote_repository_exists "$git_repository_ssh_url"; then
  output::empty_line
  output::error "🚨 The given git url does not exists or could not get access to."
  output::empty_line
fi

start_path="$(pwd)"
cd "$DOTFILES_PATH" || {
  output::error "DOTFILES_PATH not found"
  exit 1
}

if $recreate && [[ -d "$DOTLY_SECRETS_MODULE_PATH" ]] ; then
  output::empty_line
  output::header "WARNING!"
  output::write "You are doing a dangerous action. This will delete all your current secrets."
  output::write "This means that you will delete stored files and vars that could be not "
  output::write "commited to your secrets repository."
  output::yesno "Are you sure you want to continue" || { output::error "User aborted"; exit 1; }

  "$DOTLY_PATH/bin/dot" secrets apply --revert
  git submodule deinit -f -- "$DOTLY_SECRETS_MODULE_PATH"
  rm -rf ".git/modules/$DOTLY_SECRETS_MODULE_PATH"
  git rm -f --cached "$DOTLY_SECRETS_MODULE_PATH"
  secrets_bk_path="$DOTFILES_PATH/$DOTLY_SECRETS_MODULE_PATH.$(date +%s)"
  mv "$DOTLY_SECRETS_MODULE_PATH" "$secrets_bk_path"
  output::empty_line
  output::answer "Your current secrets were moved to:"
  output::answer  "$secrets_bk_path"
  output::empty_line
  output::error "The secrets were not removed, do it by YOUR OWN RISK if you want by executing manually:"
  output::error "rm -rf $secrets_bk_path"
  output::empty_line
  output::error "IS IMPORTANT TO move or remove outside your DOTFILES_PATH because you can append your secrets to your dotfiles repository now."
  output::empty_line
fi

git submodule add -b "${branch:-master}" "$git_repository_ssh_url" "$DOTLY_SECRETS_MODULE_PATH"

"$DOTLY_PATH/bin/dot" secrets apply


cd "$start_path" || exit
