#!/usr/bin/env bash

[[ -z "$DOTLY_PATH" ]] && exit 1

. "$DOTLY_PATH/scripts/core/_main.sh"
. "$DOTLY_PATH/scripts/secrets/lib/secrets.sh"

##? Load secret variables by executing this command
##? 
##?
##? Usage:
##?   load [-h | --help]
##?   load [-v | --version]
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
docs::parse "$@"

SCRIPT_NAME="dot secrets load"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

secrets::load_vars
output::answer "All secret variables loaded"

# { [[ -f "$DOTFILES_PATH/modules/secrets/init-scripts/secrets_autoload" ]] &&\
#   exec "$DOTFILES_PATH/modules/secrets/init-scripts/secrets_autoload" &&\
#   output::answer "All secret variables loaded"
# } || output::error "Can not be loaded, are you sure you have your secrets initiliazed?"