#!/usr/bin/env bash

[[ -z "$DOTLY_PATH" ]] && exit 1

. "$DOTLY_PATH/scripts/core/_main.sh"
. "$DOTLY_PATH/scripts/secrets/lib/secrets.sh"

purge_files() {
  output::answer "📁 Removing files"
  secrets::find --exclude files | while read -r item; do
    secrets::check_exists "files/$item" && secrets::remove_file "files/$item"
  done
  secrets::purge_secrets_json
}

purge_vars() {
  output::answer "λ Removing vars"
  secrets::find --exclude vars | while read -r item; do
    secrets::check_exists "vars/$item" && secrets::remove_file "vars/$item"
  done
}

##? Purge all vars and files files
##? 
##?
##? Usage:
##?   purge [-h | --help]
##?   purge [-v | --version]
##?   purge [files|vars] [-n | --no-sync]
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?   -n --no-sync  Do not sync changes
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
docs::parse "$@"

SCRIPT_NAME="dot secrets purge"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

output::header "🗑 Purging"
case "$1"; in
"vars")
  purge_vars
  ;;
"files")
  purge_files
  ;;
*)
  purge_vars
  purge_files
  ;;
esac

# TODO enable sync
# if ! $no_sync; then
#   "$DOTLY_PATH/bin/dot" secrets sync
# fi
