#!/usr/bin/env bash

[[ -z "$DOTLY_PATH" ]] && exit 1

. "$DOTLY_PATH/scripts/core/_main.sh"
. "$DOTLY_PATH/scripts/secrets/lib/secrets.sh"

##? Handle stored secrets
##? 
##?
##? Usage:
##?   store [-h | --help]
##?   store [-v | --version]
##?   store [-p | --prompt] [-n | --no-sync]  <item_path> [<secrets_subfolder>]
##?   store edit [-n | --no-sync] [<item_path> [<new_symlink_path>]] 
##?   store edit [<secret_path>]
##?   store delete [<secret_path>] 
##?   store purge 
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?   -p --prompt   Ask subfolder path to store the file
##?   -n --no-sync  Do not sync changes
##?   --message     Change default sync message to defined message
##?   edit          Edit a secret providing the relative path to
##?                 `$DOTFILES_PATH/modules/secrets/files` if you do
##?                 not provide any it will show a output with fzf to
##?                 select the file(s) you want to edit.
##?   delete        Delete a secret providing the relative path to
##?                 `$DOTFILES_PATH/modules/secrets/files` if you do
##?                 not provide any it will show a output with fzf to
##?                 select the file(s) you want to delete.
##?   purge         Delete all stored secrets in
##?                    `$DOTFILES_PATH/modules/secrets/files`
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
docs::parse "$@"

SCRIPT_NAME="dot secrets store"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

case $1 in
"delete")
  echo "Not implemented"
  ;;
"edit")
  echo "Not implemented"
  # TODO Edit current symlink to another one for secret file
  ;;
"restore")
  ;;
*)
  if $prompt && [[ -z "${secrets_subfolder:-}" ]]; then
    output::question "Relative path inside secrets files subfolder" "secrets_subfolder"
  fi
  
  secrets::store "$item_path" "${secrets_subfolder:-}"
  ;;
esac

# TODO enable sync
# if ! $no_sync; then
#   "$DOTLY_PATH/bin/dot" secrets sync
# fi
