#!/usr/bin/env bash

[[ -z "$DOTLY_PATH" ]] && exit 1

. "$DOTLY_PATH/scripts/core/_main.sh"
. "$DOTLY_PATH/scripts/secrets/lib/secrets.sh"

##? Handle stored secrets
##? 
##?
##? Usage:
##?   store [-h | --help]
##?   store [-v | --version]
##?   store [-p | --prompt] [-n | --no-sync]  <item_path> [<secrets_subfolder>]
##?   store edit [-n | --no-sync] [<item_path> [<new_symlink_path>]] 
##?   store edit [-n | --no-sync] [<secret_path>]
##?   store delete [-n | --no-sync] [<secret_path>]
##?   store purge [-n | --no-sync]
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?   -p --prompt   Ask subfolder path to store the file
##?   -n --no-sync  Do not sync changes
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
docs::parse "$@"

SCRIPT_NAME="dot secrets store"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

case $1 in
"delete")
  # Provided file
  if [[ -n "${2:-}" ]]; then
    file_secret_path="$(secrets::check_exists "files/$2")"
    if [[ -z $file_secret_path ]]; then
      output::error "🗃 Eror 404: File not found"
      exit 1
    fi

    secrets::remove_symlink_by_stored_file "$2"
    exit 0
  fi

  # Not provided file
  deleted_items=($(secrets::find --exclude files | secrets::fzf "Select file(s) to be deleted"))
  for item in "${deleted_items[@]}"; do
    secrets::remove_symlink_by_stored_file "$item"
  done
  ;;
"purge")
  echo "Purging"
  # secrets::find --exclude files | while read -r item; do
  #   echo "$item"
  # done

  #secrets::purge 
  ;;
"edit")
  echo "Not implemented"
  # TODO Edit current symlink to another one for secret file
  ;;
"restore")
  ;;
*)
  if $prompt && [[ -z "${secrets_subfolder:-}" ]]; then
    output::question "Relative path inside secrets files subfolder" "secrets_subfolder"
  fi
  
  secrets::store "$item_path" "${secrets_subfolder:-}"
  ;;
esac

# TODO enable sync
# if ! $no_sync; then
#   "$DOTLY_PATH/bin/dot" secrets sync
# fi
