#!/usr/bin/env bash

[[ -z "$DOTLY_PATH" ]] && exit 1

. "$DOTLY_PATH/scripts/core/_main.sh"
. "$DOTLY_PATH/scripts/secrets/lib/secrets.sh"

##? Handle stored secrets
##? 
##?
##? Usage:
##?   store [-h | --help]
##?   store [-v | --version]
##?   store [-p | --prompt] [[-n | --no-sync] | [--message=*]]  <path> [<subfolder>]
##?   store edit [[-n | --no-sync] | [--message=*]] [<secret_path> [<new_symlink_path>]] 
##?   store delete [<secret_path>] 
##?   store purge 
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?   -p --prompt   Ask subfolder path to store the file
##?   -n --no-sync  Do not sync changes
##?   --message     Change default sync message to defined message
##?   edit          Edit a secret providing the relative path to
##?                 `$DOTFILES_PATH/modules/secrets/files` if you do
##?                 not provide any it will show a output with fzf to
##?                 select the file(s) you want to edit.
##?   delete        Delete a secret providing the relative path to
##?                 `$DOTFILES_PATH/modules/secrets/files` if you do
##?                 not provide any it will show a output with fzf to
##?                 select the file(s) you want to delete.
##?   purge         Delete all stored secrets in
##?                    `$DOTFILES_PATH/modules/secrets/files`
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
docs::parse "$@"

SCRIPT_NAME="dot secrets store"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

# Here begin your script
foo="/Users/gtrabanco/.dotfiles/symlinks"
echo ${foo//$HOME/\~}
echo ${foo//$HOME/\$HOME}

case $1 in
"edit")
  # TODO Edit current symlink to another one for secret file
  ;;
*)
  # TODO
  # TODO -p | --prompt ask user for subfolder path inside secrets/files/ to store the secret file
  # TODO If not prompt it will use $(dirname $(pwd)/$path) or $(dirname $path) as secrets/file subfolder
  ;;
esac

if ! $no_sync; then
  "$DOTLY_PATH/bin/dot" secrets sync
fi