#!/usr/bin/env bash

[[ -z "$DOTLY_PATH" ]] && exit 1

. "$DOTLY_PATH/scripts/core/_main.sh"
. "$DOTLY_PATH/scripts/secrets/lib/secrets.sh"

##? Synchronized your current secrets with your remote 'origin' repository
##? and apply current secrets symlinks
##?
##? Usage:
##?   sync [-h | --help]
##?   sync [-v | --version]
##?   sync [-n | --no-apply]
##?
##? Options:
##?   -h --help      Show this help
##?   -v --version   Show the program version
##?   -n --no-apply  Not apply symlinks
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
docs::parse "$@"

SCRIPT_NAME="dot secrets sync"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

if ! secrets::check_exists >/dev/null; then
  output::error "Your secrets can not be found. Have you initialize your secrets?"
  exit 1
fi

start_dir="$(pwd)"
cd "$DOTFILES_PATH/$DOTLY_SECRETS_MODULE_PATH" || {
  output::error "🏁 Have you initilized your secrets repository?"
  exit 1
}

output::header "Syncronizing your secrets"

{
  git add . >/dev/null 2>&1 &&\
  git stash >/dev/null 2>&1 &&\
  git pull >/dev/null 2>&1 &&\
  git stash pop >/dev/null 2>&1 &&\
  git add . >/dev/null 2>&1 &&\
  git commit -m "Update $(date +%s)" >/dev/null 2>&1 &&\
  git push origin master >/dev/null 2>&1 &&\
  output::solution "📤 Your secrets were synchronized"
} || {
  output::error "😅 Nothing to sync"
  cd "$start_dir" || true
  exit
}

cd "$start_dir" || true

if ! $no_apply; then
  "$DOTLY_PATH/bin/dot" secrets apply
fi
