#!/usr/bin/env bash

[[ -z "$DOTLY_PATH" ]] && exit 1

. "$DOTLY_PATH/scripts/core/_main.sh"
. "$DOTLY_PATH/scripts/secrets/lib/secrets.sh"

##? Synchronized your current secrets with your remote 'origin' repository by executing:
##? 'git pull && git add . &&\
##?    git commit -m "Update secrets $(date %s)" &&\
##?    git push origin master
##? Also apply aliases
##?
##? Usage:
##?   sync [-h | --help]
##?   sync [-v | --version]
##?   sync [--revert]
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
docs::parse "$@"

SCRIPT_NAME="dot secrets sync"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

echo "Not implemented"
# Here begin your script
# TODO
##? 'git pull && git add . &&\
##?    git commit -m "Update secrets $(date %s)" &&\
##?    git push origin master

# Apply aliases
#"$DOTLY_PATH/bin/dot" secrets apply