#!/usr/bin/env bash

[[ -z "$DOTLY_PATH" ]] && exit 1

. "$DOTLY_PATH/scripts/core/_main.sh"
. "$DOTLY_PATH/scripts/secrets/lib/secrets.sh"

##? Synchronized your current secrets with your remote 'origin' repository
##? and apply current secrets symlinks
##?
##? Usage:
##?   sync [-h | --help]
##?   sync [-v | --version]
##?   sync [-n | --no-apply] [-y | --yes]
##?
##? Options:
##?   -h --help      Show this help
##?   -v --version   Show the program version
##?   -n --no-apply  Not apply symlinks
##?   -y --yes       Not prompt if you are sure about you will want to do
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
docs::parse "$@"

SCRIPT_NAME="dot secrets sync"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

if ! secrets::check_exists >/dev/null; then
  output::error "Your secrets can not be found. Have you initialize your secrets?"
  exit 1
fi

start_dir="$(pwd)"
cd "$DOTFILES_PATH/$DOTLY_SECRETS_MODULE_PATH" || {
  output::error "🏁 Have you initilized your secrets repository?"
  exit 1
}

output::header "Syncronizing your secrets"

if ! $yes; then
  output::empty_line
  output::error "🚨🚨🚨🚨 WARNING! 🚨🚨🚨🚨"
  output::empty_line
  output::write "Syncronize your secrets could delete some files. If you have deleted those"
  output::write "files across the commits and you do not have a backup in any other safe"
  output::write "place, you can lost your files forever."
  output::write "- 😱 Forever? 😥 🙀 😰"
  output::write "- 😥 Yes."
  output::write "- 🙀 Nothing is deleted forever."
  output::write "- 😰 Well, I am just a dev. Decision is up to you."
  output::empty_line
  output::yesno "Are you sure you want to continue" || {
    output::error "User aborted"
    exit 1
  }
  output::empty_line
fi

{
  git add . >/dev/null 2>&1 &&\
  git stash >/dev/null 2>&1 &&\
  git pull >/dev/null 2>&1 &&\
  git stash pop >/dev/null 2>&1 &&\
  git add . >/dev/null 2>&1 &&\
  git commit -m "Update $(date +%s)" >/dev/null 2>&1 &&\
  git push origin master --force >/dev/null 2>&1 &&\
  output::solution "📤 Your secrets were synchronized"
} || {
  output::error "😅 Nothing to sync"
  cd "$start_dir" || true
  exit
}

cd "$start_dir" || true

if ! $no_apply; then
  "$DOTLY_PATH/bin/dot" secrets apply
fi
