#!/usr/bin/env bash

[[ -z "$DOTLY_PATH" ]] && exit 1

. "$DOTLY_PATH/scripts/core/_main.sh"
. "$DOTLY_PATH/scripts/secrets/lib/secrets.sh"

##? Set, get and delete variable values
##? 
##?
##? Usage:
##?   var [-h | --help]
##?   var [-v | --version]
##?   var [-d | --delete] <var_name> [<value>...]
##?
##? Options:
##?   -h --help     Show this help
##?   -v --version  Show the program version
##?   -d --delete   Delete var_name if exists
##?
##? Author:
##?   Gabriel Trabanco Llano <gtrabanco@users.noreply.github.com>
##?
docs::parse "$@"

SCRIPT_NAME="dot secrets hide"
SCRIPT_VERSION="1.0.0"

# Print name and version
if ${version:-}; then
  output::write "$SCRIPT_NAME v$SCRIPT_VERSION"
  exit
fi

if $delete; then
  secrets::var_delete "$var_name"
  unset "$var_name"
  exit 0
fi

secrets::var "$var_name" "${value[*]:-}"

# TODO enable sync
# if ! $no_sync; then
#   "$DOTLY_PATH/bin/dot" secrets sync
# fi
